---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: empms-webserver
  name: empms-webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: empms-webserver
  template:
    metadata:
      labels:
        app: empms-webserver
    spec:
      containers:
      - image: opstree/empms-webserver:1.0
        imagePullPolicy: Always
        name: empms-webserver
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: empms-webserver
spec:
  type: LoadBalancer
  selector:
    app: empms-webserver
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
